### ISSUE TITLE
pom.xml does not build src/main.java

### ISSUE THREAD

**Issue by monperrus** [Adobee/ACS#1]
Hi,

I'm running the following standard commands

    git clone https://github.com/Adobee/ACS
    mvn compile

it does not seem to compile the code in `src/main.java` in `./target`. (it only compiles and create `./RunTestAgent/target`

Is this a bug in pom.xml?

**Comment by hhxx12ttxs** [comment]
Hi,we did not use maven, you can try intellij

**Comment by xiongyingfei** [comment]
I just saw this issue. @hhxx12ttxs @Adobee It is better to add a new section "How to compile ACS" to readme.md
