### ISSUE TITLE
Where is the result?

### ISSUE THREAD

**Issue by Kaka727** [Adobee/ACS#2]
Is there a document to record the experiment results automatically after executing the command "java -jar ACS.jar /tmp/"???

**Comment by xiongyingfei** [comment]
The results are in the dir "ACS/resultMessage", the detailed patch is in the file "ACS/resultMessage/patchSource/Project_BugId_Schema_PatchId.java"(If a bug has n patches, the "PatchId" will range from 0 to n - 1), and is between "patch begin" and "patch end".
