### ISSUE TITLE
Would it be possible/easy to run ACS on any other bug than a D4J bug?

### ISSUE THREAD

**Issue by jose** [Adobee/ACS#6]
Hi,

It seems ACS is kinda dependent on D4J's structure and bugs, e.g.,
> the forder name of checkout must format as 'ProjectName_buggyID' because the ACS needs it's project name and buggy id to generate it's classpath, source path etc.

I'm wondering whether would it be possible (and easy) to run ACS on any other bug than D4J's bugs? If yes, it would be great if could help me on that.

Thanks in advance.

--
Best,
Jose

**Comment by xiongyingfei** [comment]
Below is a quote from readme.md.
>> ACS can no longer execute on new bugs. The execution of ACS requires querying of GitHub, but GitHub recently changed its interface and does not allow programmed queries. Therefore, the original code of ACS cannot execute normally and there is no easy way to fix that. ACS can still run on the original Defects4J bugs as the results were cached.

>> If you are looking for a modern program repair tool on Java for experiments or for building your own, we would recommend our newest tool SimFix: https://github.com/xgdsmileboy/SimFix

So unfortunately ACS does not run on new bugs anymore.
